server:
  port: 443
  servlet:
    context-path: /Shopme
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: Shopme123!
    key-store-password: Shopme123!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 108477698869-v3ob00sfb9j96s4i60gjg38vuup5rdln.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 373793972162541
            client-secret: 40dd7ba6ba495ec8380081f97f25b953
            scope:
              - email
              - public_profile