server:
  port: 80
  servlet:
    context-path: /Shopme

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 108477698869-v3ob00sfb9j96s4i60gjg38vuup5rdln.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile