server:
  port: 8443
  servlet:
    context-path: /ShopmeAdmin
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: Shopme123!
    key-store-password: Shopme123!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
